Document: dltselftestapp
Title: Debian dltselftestapp Manual
Author: <insert document author here>
Abstract: This manual describes what dltselftestapp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dltselftestapp/dltselftestapp.sgml.gz

Format: postscript
Files: /usr/share/doc/dltselftestapp/dltselftestapp.ps.gz

Format: text
Files: /usr/share/doc/dltselftestapp/dltselftestapp.text.gz

Format: HTML
Index: /usr/share/doc/dltselftestapp/html/index.html
Files: /usr/share/doc/dltselftestapp/html/*.html
